import { Header } from "@/components/header"
import { ProductDetails } from "@/components/product-details"
import { Footer } from "@/components/footer"
import { notFound } from "next/navigation"

export const products = {
  "1": {
    id: "1",
    name: "Icons - McLaren MP4/4 e Ayrton Senna",
    price: 499.99,
    originalPrice: null,
    rating: 5.0,
    reviews: 156,
    ages: "8+",
    pieces: 693,
    itemNumber: "76230",
    vipPoints: 1875,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/185202/10330--1-.jpg?v=638424970071170000",
      "https://legobrasil.vtexassets.com/arquivos/ids/185200/10330.jpg?v=638424969949830000",
      "https://legobrasil.vtexassets.com/arquivos/ids/185203/10330--2-.jpg?v=638424970785870000",
      "https://legobrasil.vtexassets.com/arquivos/ids/185208/10330--8-.jpg?v=638424971650770000",
    ],
    description:
      "A réplica do McLaren MP4/4 apresenta direção funcional, suspensão de haste, asa traseira ajustável, pneus slick, espelhos, câmbio de marchas e motor V6 turboalimentado detalhado, além de expositor e placa informativa com estatísticas interessantes. A minifigura de Ayrton Senna vem com um expositor estilo pódio e uma placa informativa com uma citação e foto icônica de Ayrton Senna.",
    features: [],
    inStock: true,
    puzzleImage: "https://legobrasil.vtexassets.com/arquivos/ids/185202/10330--1-.jpg?v=638424970071170000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 70,
    categories: ["speedchampions"],
  },
  "2": {
    id: "2",
    name: "Disney - Mini Castelo da Disney",
    price: 329.99,
    originalPrice: null,
    rating: 4.9,
    reviews: 203,
    ages: "8+",
    pieces: 1456,
    itemNumber: "31212",
    vipPoints: 1500,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/176770/lego_40478_Disney_Mini_Castelo_da_Disney_01.jpg?v=637732735262400000",
    ],
    description:
      "Construa, brinque e exiba! Este incrível conjunto LEGO oferece uma experiência de construção envolvente com peças de alta qualidade e detalhes autênticos. Perfeito para fãs de todas as idades, este conjunto proporciona horas de diversão criativa e é ideal para exibição. Inclui instruções passo a passo e elementos únicos que tornam cada construção especial. Desperte sua imaginação e crie memórias duradouras com este fantástico conjunto LEGO.",
    features: [],
    inStock: true,
    puzzleImage:
      "https://legobrasil.vtexassets.com/arquivos/ids/176770/lego_40478_Disney_Mini_Castelo_da_Disney_01.jpg?v=637732735262400000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 20,
    categories: ["disney"],
  },
  "3": {
    id: "3",
    name: "Mala de Viagem Amarela",
    price: 149.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 89,
    ages: "7+",
    pieces: 184,
    itemNumber: "21333",
    vipPoints: 1500,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/189242/40817.jpg?v=638768033043630000",
      "https://legobrasil.vtexassets.com/arquivos/ids/189248/40817--6-.jpg?v=638768033863470000",
    ],
    description:
      "Pegue seu passaporte e prepare-se para a aventura com este kit de construção de modelo de mala de viagem LEGO® Yellow Travel Suitcase (40817). Este conjunto com tema de férias é um presente divertido para crianças de 7 anos ou mais, ou qualquer pessoa que ame viajar. A mini mala possui uma alça retrátil, rodas funcionais e uma etiqueta de bagagem. Abra a mala para embalar a câmera, o cartão de embarque, a escova de dentes e o passaporte - divirta-se fazendo tudo caber! O conjunto vem com uma folha de adesivos divertida para personalizar a parte externa da mala.",
    features: [
      "Recriação autêntica dos Girassóis de van Gogh",
      "Inclui moldura decorativa para pendurar na parede",
      "Técnica única de construção de arte LEGO",
      "Vem com minifigura de van Gogh",
      "Livreto de informações sobre história da arte incluído",
    ],
    inStock: true,
    puzzleImage: "https://legobrasil.vtexassets.com/arquivos/ids/189242/40817.jpg?v=638768033043630000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 15,
    categories: ["icons"],
  },
  "4": {
    id: "4",
    name: "Minecraft® - Ringue de luta da mansão Woodland",
    price: 479.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 89,
    ages: "7+",
    pieces: 491,
    itemNumber: "21333",
    vipPoints: 1500,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/189063/21272.jpg?v=638738549970430000",
      "https://legobrasil.vtexassets.com/arquivos/ids/189069/21272--6-.jpg?v=638738553786900000",
    ],
    description:
      "O conjunto de construção LEGO® Minecraft apresenta figuras de brinquedo do filme – Steve, Garrett, Henry, um bebê zumbi, um jóquei de galinha e um porco grande posável – além de armas e poções que as crianças podem usar enquanto recriam cenas de batalha e exploram suas próprias aventuras. O conjunto apresenta um ringue de luta funcional com marcadores de pontuação e alças que as crianças podem prender aos lutadores. Há também uma fachada de mansão com um baú removível e suporte para armas. Para diversão digital, o aplicativo LEGO Builder permite que as crianças ampliem, girem modelos em 3D e acompanhem seu progresso.",
    features: [
      "Recriação autêntica dos Girassóis de van Gogh",
      "Inclui moldura decorativa para pendurar na parede",
      "Técnica única de construção de arte LEGO",
      "Vem com minifigura de van Gogh",
      "Livreto de informações sobre história da arte incluído",
    ],
    inStock: true,
    puzzleImage: "https://legobrasil.vtexassets.com/arquivos/ids/189063/21272.jpg?v=638738549970430000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 15,
    categories: ["minecraft"],
  },
  "5": {
    id: "5",
    name: "Speed Champions - Ferrari F40 Supercar",
    price: 479.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 89,
    ages: "7+",
    pieces: 318,
    itemNumber: "21333",
    vipPoints: 1500,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/187718/76934.jpg?v=638646997377600000",
      "https://legobrasil.vtexassets.com/arquivos/ids/187726/76934--10-.jpg?v=638646998339130000",
    ],
    description:
      "Meninos e meninas com mais de 9 anos podem colecionar, construir, brincar e exibir este incrível brinquedo de carro LEGO® Speed Champions Ferrari F40 (76934). Projetado para celebrar o 40º aniversário da icônica marca de carros italiana, o F40 foi o último modelo aprovado pessoalmente pelo fundador da Ferrari, Enzo Ferrari, e este fantástico veículo montável para crianças apresenta muitos detalhes de design famosos da versão da vida real.",
    features: [
      "Recriação autêntica dos Girassóis de van Gogh",
      "Inclui moldura decorativa para pendurar na parede",
      "Técnica única de construção de arte LEGO",
      "Vem com minifigura de van Gogh",
      "Livreto de informações sobre história da arte incluído",
    ],
    inStock: true,
    puzzleImage: "https://legobrasil.vtexassets.com/arquivos/ids/189063/21272.jpg?v=638738549970430000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 15,
    categories: ["speedchampions"],
  },
  "6": {
    id: "6",
    name: "Harry Potter™ - Passeio de moto de Hagrid™ e Harr",
    price: 479.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 89,
    ages: "7+",
    pieces: 617,
    itemNumber: "21333",
    vipPoints: 1500,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/188029/76443.jpg?v=638689283624800000",
      "https://legobrasil.vtexassets.com/arquivos/ids/188035/76443--6-.jpg?v=638689285167900000",
    ],
    description:
      "Segure firme para o Passeio de Motocicleta de Hagrid™ e Harry (76443) com este brinquedo mágico para meninas, meninos e qualquer fã do Mundo Mágico. Um presente de aniversário legal para crianças de 9 anos ou mais, este conjunto de brincar e exibir LEGO® Harry Potter™ apresenta figuras de brinquedo Harry Potter, Hedwig™ e Rubeus Hagrid integradas e articuladas andando em uma motocicleta e em seu sidecar. As rodas do brinquedo de veículo construído com peças LEGO giram para que as crianças possam encenar cenas icônicas de Harry Potter e as Relíquias da Morte™, ou o modelo pode ser exibido como uma decoração impressionante de quarto de Harry Potter.",
    features: [
      "Representação cientificamente precisa da galáxia",
      "Mecanismo de braços espirais rotativos",
      "Sistema de iluminação LED incluído",
      "Livreto de informações educacionais",
      "Base de exibição premium com placa de identificação",
    ],
    inStock: true,
    puzzleImage: "https://legobrasil.vtexassets.com/arquivos/ids/188029/76443.jpg?v=638689283624800000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 15,
    categories: ["harrypotter"],
  },
  "7": {
    id: "7",
    name: "Creator - Modelo 3 Em 1: Dinossauros Ferozes",
    price: 149.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 89,
    ages: "7+",
    pieces: 174,
    itemNumber: "21333",
    vipPoints: 1500,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/170220/31058_prod.jpg?v=637111671490100000",
      "https://legobrasil.vtexassets.com/arquivos/ids/170223/31058_box1_v29.jpg?v=638773831184270000",
    ],
    description:
      "Segure firme para o Passeio de Motocicleta de Hagrid™ e Harry (76443) com este brinquedo mágico para meninas, meninos e qualquer fã do Mundo Mágico. Um presente de aniversário legal para crianças de 9 anos ou mais, este conjunto de brincar e exibir LEGO® Harry Potter™ apresenta figuras de brinquedo Harry Potter, Hedwig™ e Rubeus Hagrid integradas e articuladas andando em uma motocicleta e em seu sidecar. As rodas do brinquedo de veículo construído com peças LEGO giram para que as crianças possam encenar cenas icônicas de Harry Potter e as Relíquias da Morte™, ou o modelo pode ser exibido como uma decoração impressionante de quarto de Harry Potter.",
    features: [
      "Recriação autêntica dos Girassóis de van Gogh",
      "Inclui moldura decorativa para pendurar na parede",
      "Técnica única de construção de arte LEGO",
      "Vem com minifigura de van Gogh",
      "Livreto de informações sobre história da arte incluído",
    ],
    inStock: true,
    puzzleImage: "https://legobrasil.vtexassets.com/arquivos/ids/170220/31058_prod.jpg?v=637111671490100000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 15,
    categories: ["creator"],
  },
  "8": {
    id: "8",
    name: "Ideas - Magia da Disney",
    price: 759.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 89,
    ages: "7+",
    pieces: 1103,
    itemNumber: "21333",
    vipPoints: 1500,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/187552/21352.jpg?v=638621859108970000",
      "https://legobrasil.vtexassets.com/arquivos/ids/187556/21352--4-.jpg?v=638621859598330000",
    ],
    description:
      "Com Mickey Mouse em sua roupa de aprendiz de feiticeiro no centro, este modelo colecionável exibe muitos personagens populares da Disney e inclui a primeira minifigura LEGO de Bela de A Bela e a Fera com a rosa encantada. Outras vinhetas incluem Gepeto em uma jangada em Pinóquio, Lilo surfando em Lilo & Stitch, Simba no topo da Pride Rock em O Rei Leão, Bruno na Madrigal House em Encanto, as vassouras mágicas carregando água em Fantasia e Sebastião, o caranguejo, e Linguado, o peixe em A Pequena Sereia.",
    features: [
      "Recriação autêntica dos Girassóis de van Gogh",
      "Inclui moldura decorativa para pendurar na parede",
      "Técnica única de construção de arte LEGO",
      "Vem com minifigura de van Gogh",
      "Livreto de informações sobre história da arte incluído",
    ],
    inStock: true,
    puzzleImage: "https://legobrasil.vtexassets.com/arquivos/ids/187552/21352.jpg?v=638621859108970000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 15,
    categories: ["disney"],
  },
  "9": {
    id: "9",
    name: "City - Avião de Passageiros",
    price: 799.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 89,
    ages: "7+",
    pieces: 913,
    itemNumber: "21333",
    vipPoints: 1500,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/184072/60367-lego-city-aviao-de-passageiros.jpg?v=638276417925400000",
      "https://legobrasil.vtexassets.com/arquivos/ids/184075/60367-lego-city-aviao-de-passageiros--4-.jpg?v=638276418801630000",
    ],
    description:
      "Aqui está um agrado para fãs de modelos de aviões. Este conjunto LEGO® City Avião de Passageiros (60367) está repleto de recursos e funções realistas. O avião super elegante tem um interior detalhado com um cockpit, assentos, um corredor, banheiro e inclui uma escada de embarque, ônibus de embarque, trator de reboque, caminhão de comidas e caminhão de bagagem, além de 9 minifiguras para inspirar brincadeiras.",
    features: [
      "Recriação autêntica dos Girassóis de van Gogh",
      "Inclui moldura decorativa para pendurar na parede",
      "Técnica única de construção de arte LEGO",
      "Vem com minifigura de van Gogh",
      "Livreto de informações sobre história da arte incluído",
    ],
    inStock: true,
    puzzleImage:
      "https://legobrasil.vtexassets.com/arquivos/ids/184072/60367-lego-city-aviao-de-passageiros.jpg?v=638276417925400000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 15,
    categories: ["icons"],
  },
  "10": {
    id: "10",
    name: "BrickHeadz - Ron Weasley e Alvo Dumbleodore",
    price: 299.99,
    originalPrice: null,
    rating: 4.4,
    reviews: 198,
    ages: "8+",
    pieces: 245,
    itemNumber: "HASH_F25FFD",
    vipPoints: 19,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/162852/41621_prod.jpg?v=636790186742700000",
      "https://legobrasil.vtexassets.com/arquivos/ids/162853/41621_front_02.jpg?v=636790186926770000",
      "https://legobrasil.vtexassets.com/arquivos/ids/162854/41621_front_01.jpg?v=636790187034900000",
      "https://legobrasil.vtexassets.com/arquivos/ids/162855/41621_back_01.jpg?v=636790187180300000",
    ],
    description:
      "Construa, brinque e exiba! Este incrível conjunto LEGO oferece uma experiência de construção envolvente com peças de alta qualidade e detalhes autênticos. Perfeito para fãs de todas as idades, este conjunto proporciona horas de diversão criativa e é ideal para exibição. Inclui instruções passo a passo e elementos únicos que tornam cada construção especial. Desperte sua imaginação e crie memórias duradouras com este fantástico conjunto LEGO.",
    features: [],
    inStock: true,
    puzzleImage: "https://legobrasil.vtexassets.com/arquivos/ids/162852/41621_prod.jpg?v=636790186742700000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 70,
    categories: ["harrypotter", "todos"],
  },
  "11": {
    id: "11",
    name: "Harry Potter™ - Carruagem e Testrálio de Hogwarts™",
    price: 299.99,
    originalPrice: null,
    rating: 4.4,
    reviews: 226,
    ages: "8+",
    pieces: 121,
    itemNumber: "76400",
    vipPoints: 19,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/180431/76400_Lego_Harry_Potter_Carruagem_e_Testralio_de_Hogwarts_01.jpg?v=637976600125630000",
      "https://legobrasil.vtexassets.com/arquivos/ids/180432/76400_Lego_Harry_Potter_Carruagem_e_Testralio_de_Hogwarts_02.jpg?v=637976600207200000",
      "https://legobrasil.vtexassets.com/arquivos/ids/180433/76400_Lego_Harry_Potter_Carruagem_e_Testralio_de_Hogwarts_03.jpg?v=637976600287970000",
      "https://legobrasil.vtexassets.com/arquivos/ids/180434/76400_Lego_Harry_Potter_Carruagem_e_Testralio_de_Hogwarts_04.jpg?v=637976600439230000",
    ],
    description:
      "Construa, brinque e exiba! Este incrível conjunto LEGO oferece uma experiência de construção envolvente com peças de alta qualidade e detalhes autênticos. Perfeito para fãs de todas as idades, este conjunto proporciona horas de diversão criativa e é ideal para exibição. Inclui instruções passo a passo e elementos únicos que tornam cada construção especial. Desperte sua imaginação e crie memórias duradouras com este fantástico conjunto LEGO.",
    features: [],
    inStock: true,
    puzzleImage:
      "https://legobrasil.vtexassets.com/arquivos/ids/180431/76400_Lego_Harry_Potter_Carruagem_e_Testralio_de_Hogwarts_01.jpg?v=637976600125630000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 70,
    categories: ["harrypotter", "todos"],
  },
  "12": {
    id: "12",
    name: "Harry Potter™ - O Ministério da Magia™",
    price: 299.99,
    originalPrice: null,
    rating: 4.3,
    reviews: 450,
    ages: "8+",
    pieces: 990,
    itemNumber: "HASH_05C9DF",
    vipPoints: 19,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/180467/76403_Lego_Harry_Potter_O_Ministerio_da_Magia_01.jpg?v=637977279760200000",
      "https://legobrasil.vtexassets.com/arquivos/ids/180468/76403_Lego_Harry_Potter_O_Ministerio_da_Magia_02.jpg?v=637977279852330000",
      "https://legobrasil.vtexassets.com/arquivos/ids/180469/76403_Lego_Harry_Potter_O_Ministerio_da_Magia_03.jpg?v=637977280172800000",
      "https://legobrasil.vtexassets.com/arquivos/ids/180470/76403_Lego_Harry_Potter_O_Ministerio_da_Magia_04.jpg?v=637977280249370000",
    ],
    description:
      "Construa, brinque e exiba! Este incrível conjunto LEGO oferece uma experiência de construção envolvente com peças de alta qualidade e detalhes autênticos. Perfeito para fãs de todas as idades, este conjunto proporciona horas de diversão criativa e é ideal para exibição. Inclui instruções passo a passo e elementos únicos que tornam cada construção especial. Desperte sua imaginação e crie memórias duradouras com este fantástico conjunto LEGO.",
    features: [],
    inStock: true,
    puzzleImage:
      "https://legobrasil.vtexassets.com/arquivos/ids/180467/76403_Lego_Harry_Potter_O_Ministerio_da_Magia_01.jpg?v=637977279760200000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 70,
    categories: ["harrypotter", "todos"],
  },
  "13": {
    id: "13",
    name: "Harry Potter™ - O Covil de Aragogue",
    price: 299.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 53,
    ages: "8+",
    pieces: 157,
    itemNumber: "HASH_8CA641",
    vipPoints: 19,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/162277/75950_Prod.jpg?v=636703727023800000",
      "https://legobrasil.vtexassets.com/arquivos/ids/162278/75950_detail1.jpg?v=636703727593000000",
      "https://legobrasil.vtexassets.com/arquivos/ids/162279/75950_detail2.jpg?v=636703728109930000",
      "https://legobrasil.vtexassets.com/arquivos/ids/162280/75950_detail3.jpg?v=636703729245230000",
    ],
    description:
      "Construa, brinque e exiba! Este incrível conjunto LEGO oferece uma experiência de construção envolvente com peças de alta qualidade e detalhes autênticos. Perfeito para fãs de todas as idades, este conjunto proporciona horas de diversão criativa e é ideal para exibição. Inclui instruções passo a passo e elementos únicos que tornam cada construção especial. Desperte sua imaginação e crie memórias duradouras com este fantástico conjunto LEGO.",
    features: [],
    inStock: true,
    puzzleImage: "https://legobrasil.vtexassets.com/arquivos/ids/162277/75950_Prod.jpg?v=636703727023800000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 70,
    categories: ["harrypotter", "todos"],
  },
  "14": {
    id: "14",
    name: "Harry Potter™ - Calendario do Advento",
    price: 299.99,
    originalPrice: null,
    rating: 4.1,
    reviews: 492,
    ages: "8+",
    pieces: 305,
    itemNumber: "HASH_5CE97C",
    vipPoints: 19,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/170012/75964_prod.jpg?v=637087413666270000",
      "https://legobrasil.vtexassets.com/arquivos/ids/169962/75964_top_01_02_minifigures.jpg?v=637084914045100000",
      "https://legobrasil.vtexassets.com/arquivos/ids/169963/75964_back_func_01.jpg?v=637084914436070000",
      "https://legobrasil.vtexassets.com/arquivos/ids/169965/75964_box1_v29.jpg?v=637084914738130000",
    ],
    description:
      "Construa, brinque e exiba! Este incrível conjunto LEGO oferece uma experiência de construção envolvente com peças de alta qualidade e detalhes autênticos. Perfeito para fãs de todas as idades, este conjunto proporciona horas de diversão criativa e é ideal para exibição. Inclui instruções passo a passo e elementos únicos que tornam cada construção especial. Desperte sua imaginação e crie memórias duradouras com este fantástico conjunto LEGO.",
    features: [],
    inStock: true,
    puzzleImage: "https://legobrasil.vtexassets.com/arquivos/ids/170012/75964_prod.jpg?v=637087413666270000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 70,
    categories: ["harrypotter", "todos"],
  },
  "15": {
    id: "15",
    name: "Harry Potter™ - Rua dos Alfeneiros, 4",
    price: 299.99,
    originalPrice: null,
    rating: 4.5,
    reviews: 487,
    ages: "8+",
    pieces: 797,
    itemNumber: "HASH_09F736",
    vipPoints: 19,
    images: [
      "https://legobrasil.vtexassets.com/arquivos/ids/171543/lego_harry_potter_rua_dos_alfeneiros_4_01.jpg?v=637357099304130000",
      "https://legobrasil.vtexassets.com/arquivos/ids/171544/lego_harry_potter_rua_dos_alfeneiros_4_02.jpg?v=637357099940570000",
      "https://legobrasil.vtexassets.com/arquivos/ids/171545/lego_harry_potter_rua_dos_alfeneiros_4_03.jpg?v=637357100576900000",
    ],
    description:
      "Construa, brinque e exiba! Este incrível conjunto LEGO oferece uma experiência de construção envolvente com peças de alta qualidade e detalhes autênticos. Perfeito para fãs de todas as idades, este conjunto proporciona horas de diversão criativa e é ideal para exibição. Inclui instruções passo a passo e elementos únicos que tornam cada construção especial. Desperte sua imaginação e crie memórias duradouras com este fantástico conjunto LEGO.",
    features: [],
    inStock: true,
    puzzleImage:
      "https://legobrasil.vtexassets.com/arquivos/ids/171543/lego_harry_potter_rua_dos_alfeneiros_4_01.jpg?v=637357099304130000",
    puzzleTimeLimit: 300,
    puzzleDiscount: 70,
    categories: ["harrypotter", "todos"],
  },
}

export default function ProductPage({ params, searchParams }) {
  const product = products[params.id]

  // Extract discount from URL parameters
  const discount = searchParams?.discount ? Number(searchParams.discount) : 0

  console.log("[v0] ProductPage - Discount from URL:", discount)
  console.log("[v0] ProductPage - SearchParams:", searchParams)

  if (!product) {
    notFound()
  }

  return (
    <>
      <Header />
      <ProductDetails product={product} discount={discount} />
      <Footer />
    </>
  )
}
